[terminal.shell]
program = "/bin/zsh"

[font]
size = 20.0

[font.offset]
x=2

[font.normal]
family = "iosevka"
style = "Regular"

[font.bold]
family = "iosevka"
style = "Bold"

[font.italic]
family = "iosevka"
style = "Italic"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
